Dev
ang-lex/qa-automation-java pull request #4
Opened 2022-04-09 15:46 UTC by ang-lex

2022-04-18 09:59 UTC, eslepakurov requested changes

2022-04-18 09:59 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/CutDecorator.java
> +  public static int value;
зачем состояние хранить в статике?

2022-04-18 09:59 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/Severity.java
> +  public static Severity getRandom() {
используй класс Random, для более удобоваримой читаемости кода

2022-04-18 10:50 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/CutDecorator.java
> +  public static int value;
вопрос про value или PAGE_SIZE?

2022-04-18 10:52 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/CutDecorator.java
> +  public static int value;
про value

2022-04-18 16:05 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/CutDecorator.java
> +  public static int value;
Я к ней в TimestampMessageDecorator обращаюсь

2022-04-18 16:06 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/Severity.java
> +  public static Severity getRandom() {
ок. попробую,

2022-04-23 08:12 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/Severity.java
> +  public static Severity getRandom() {
https://github.com/ang-lex/qa-automation-java/pull/4/commits/201438e00cb0d5d39855273f6497acab377fe25c

2022-04-23 08:12 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/CutDecorator.java
> +  public static int value;
https://github.com/ang-lex/qa-automation-java/pull/4/commits/f84d83a325765d00ce07c1e0e4f70fe37658f63b

2022-04-25 10:35 UTC, eslepakurov requested changes

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/CutDecorator.java
> +  public static int value;
вот прям к переменной класса? может тебе нужна такая же переменная в том классе просто? ты ее там удалил почему-то

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/MessageOrder.java
> +public enum MessageOrder {
лучше создать новый пакет и положить туда этот класс, так как к декоратору он не имеет отношения напрямую

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/Doubling.java
> +public enum Doubling {
лучше создать новый пакет и положить туда этот класс, так как к декоратору он не имеет отношения напрямую

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/Doubling.java
> +public enum Doubling {
ну или в принтер перенести

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/decorator/MessageOrder.java
> +public enum MessageOrder {
ну или в принтер перенести

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +  static ArrayList<String> printedMessages = new ArrayList<String>();
new ArrayList<>() сделай, передавать тип параметра нет смысла

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +public class MessageService {
опять по всему коду, а здесь особенно, проблемы с форматированием. Забываешь пробелы, отступы и тд
Используй Code -> Reformat code
Это очень важно

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +  public static void print(Severity level, MessageOrder messageService, String... messages) {
Вложенные иф-елсы это тонкий лед, ты сойдешь с ума если еще условие добавится
Разбивай на отдельные методы такое. Ниже по коду тоже самое.

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +  public static void print(Severity level, MessageOrder messageService, String... messages) {
Код должен из маленьких блоков состоять
Каждый блок отвечает за одну маленькую функциональность
подаешь одно - выдает другое

2022-04-25 10:35 UTC, eslepakurov commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +  public static void print(Severity level, MessageOrder messageService, String... messages) {
лучше сделать один метод принт, в него отправлять все (то есть северити, фильтры, Массив сообщений)
Затем отработать фильтры по очереди
То есть взять массив сообщений, пропустить его через первый фильтр (например, уникальность)
Затем полученный массив сообщений пропустить через второй фильтр (то есть развернуть или нет)
И потом напечатать уже полученный массив и не плодить методы принт, принтРеверс и прочее

Пример фильтра
Метод принимает два параметра  - Порядок сортировки и массив
Сортирует массив (или нет)
Отдает этот массив
Ни про что другое он не знает

2022-05-07 15:27 UTC, ang-lex commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +  static ArrayList<String> printedMessages = new ArrayList<String>();
убрал

2022-05-07 15:28 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/Doubling.java
> +public enum Doubling {
перенёс в принтер

2022-05-07 15:29 UTC, ang-lex commented on src/main/java/com/tcs/edu/decorator/MessageOrder.java
> +public enum MessageOrder {
перенёс в принтер

2022-05-07 15:31 UTC, ang-lex commented on src/main/java/com/tcs/edu/printer/MessageService.java
> +public class MessageService {
Поправил

2022-05-12 08:58 UTC, merged